# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: ".github/workflows/runGrabber.yml" # See documentation for possible values
    directory: "GetM3u8/streams.m3u8" # Location of package manifests
    schedule:
      interval: "weekly"
