name: LinkGrabber

on:
  schedule:
    - cron: '0 */3 * * *'

  pull_request:
    branches: [ main ]

  workflow_dispatch:
jobs:

  runCode:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Grab Link

        run: |
          git config --global user.email "dp247@hll.localhost"
          git config --global user.name "dp247"
          chmod +x exec_grabber.sh && ./exec_grabber.sh
          git add -A
          git commit -m "Playlist updated."
          git push
