name: LinkGrabber

on:
  schedule:
    - cron: '0 */4 * * *'

  pull_request:
    branches: [ main ]

  workflow_dispatch:
jobs:

  runCode:

    runs-on: ubuntu-latest

    steps:
      
      - uses: actions/checkout@v4
      
      - name: Grab Link

        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "Github Action"
          chmod +x exec_grabber.sh && ./exec_grabber.sh
          git add -A
          git commit -m "Playlist Update"
          git push 

          runs:
            using: 'node20'
             main: 'main.js'
