name: LinkGrabber

on:
  schedule:
    - cron: '0 */6 * * *'

  pull_request:
    branches: [ main ]

  workflow_dispatch:
jobs:

  runCode:

    runs-on: ubuntu-latest

    steps:
      # Reference a specific commit
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3
      # Reference the major version of a release
      - uses: actions/checkout@v4
      # Reference a specific version
      - uses: actions/checkout@v4.2.0
      # Reference a branch
      - uses: actions/checkout@main

      - name: Grab Link

        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "Github Action"
          chmod +x exec_grabber.sh && ./exec_grabber.sh
          git add -A
          git commit -m "Playlist updated."
          git push

          runs:
            using: 'node20'
             main: 'main.js'
